export const ADD_G_MAPS_RESPONSE = "ADD_G_MAPS_RESPONSE";
export const REMOVE_G_MAPS_RESPONSE = "REMOVE_G_MAPS_RESPONSE";
export const ADD_FORM_RESPONSE = "ADD_FORM_RESPONSE";
export const REMOVE_FORM_RESPONSE = "REMOVE_FORM_RESPONSE";
export const ADD_FORM_RESPONSE_LOADED = "ADD_FORM_RESPONSE_LOADED";
export const PLAYED_GAME_RESPONSE = "PLAYED_GAME_RESPONSE";


export const ADD_G_MAPS_DECODE = "ADD_G_MAPS_DECODE";
export const REMOVE_G_MAPS_DECODE = "REMOVE_G_MAPS_DECODE";
export const RETRIEVE_S3_DATA = "RETRIEVE_S3_DATA";
export const RETRIEVE_S3_DATA_FAILURE = "RETRIEVE_S3_DATA_FAILURE";
