/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:98053939-72bb-4cfb-9517-26327b7ac35c",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "834e479160dd4681967dd285f4090a56",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
